# Generated by Django 5.2.8 on 2025-11-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='TODO', max_length=20),
        ),
    ]
